Use zplug

diff --git a/shell/zsh/zshrc b/shell/zsh/zshrc
--- a/shell/zsh/zshrc
+++ b/shell/zsh/zshrc
@@ -22,9 +22,12 @@ setopt hist_ignore_dups         # Ignore consecutive duplicates.
 setopt hist_ignore_all_dups     # Remember only one unique copy of the command.
 setopt hist_reduce_blanks       # Remove superfluous blanks.
 setopt hist_save_no_dups        # Omit older commands in favor of newer ones.
+setopt prompt_subst             # Make sure prompt is able to be generated properly.
 
-source "$dotfiles/shell/zsh/theme_settings.zsh"
-source "$dotfiles/shell/zsh/powerlevel9k/powerlevel9k.zsh-theme"
+#source "$dotfiles/shell/zsh/theme_settings.zsh"
+#source "$dotfiles/shell/zsh/powerlevel9k/powerlevel9k.zsh-theme"
+
+source "$ZSH/oh-my-zsh.sh"
 
 # Uncomment the following line to use case-sensitive completion.
 # CASE_SENSITIVE="true"
@@ -68,7 +71,7 @@ source "$dotfiles/shell/zsh/powerlevel9k/powerlevel9k.zsh-theme"
 # Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
 # Example format: plugins=(rails git textmate ruby lighthouse)
 # Add wisely, as too many plugins slow down shell startup.
-# 
+#
 # 2017-10-20 - Tobias - I checked the repository and those are the useful plugins:
 #
 # colored-man-pages composer copybuffer copydir docker docker-compose
@@ -78,11 +81,118 @@ source "$dotfiles/shell/zsh/powerlevel9k/powerlevel9k.zsh-theme"
 # vi-mode virtualenv
 #
 # Repository: https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins
-plugins=(colored-man-pages copybuffer copydir docker docker-compose git \
-		git-flow-avh git-extras gpg-agent httpie \
-		pass screen vi-mode)
 
-source "$ZSH/oh-my-zsh.sh"
+ZPLUG_INSTALLED='/usr/local/opt/zplug/installed'
+ZPLUG_HOME='/usr/local/opt/zplug/home'
+ZPLUG_BIN='/usr/local/bin'
+source $ZPLUG_INSTALLED/init.zsh
+#zplug "plugins/colored-man-pages", from:oh-my-zsh
+zplug "plugins/copybuffer", from:oh-my-zsh
+zplug "plugins/copydir", from:oh-my-zsh
+zplug "plugins/docker", from:oh-my-zsh
+zplug "plugins/docker-compose", from:oh-my-zsh
+zplug "plugins/git-fast", from:oh-my-zsh
+zplug "plugins/git-flow-avh", from:oh-my-zsh
+zplug "plugins/gpg-agent", from:oh-my-zsh
+zplug "plugins/httpie", from:oh-my-zsh
+zplug "plugins/pass", from:oh-my-zsh
+
+zplug 'zplug/zplug', hook-build:'zplug --self-manage'
+
+#zplug "sharkdp/fd", from:gh-r, as:command, rename-to:fd, use:"x86_64-unknown-linux-gnu.tar.gz"
+#zplug "junegunn/fzf-bin", from:gh-r, as:command, rename-to:fzf, use:"*linux_amd64*"
+zplug "junegunn/fzf", from:github, as:command, rename-to:fzf, hook-build:"./install --all"
+zplug "stedolan/jq", from:gh-r, as:command, rename-to:jq
+zplug "so-fancy/diff-so-fancy", from:github, as:command, rename-to:diff-so-fancy
+zplug "supercrabtree/k"
+zplug "zsh-users/zsh-syntax-highlighting", defer:2
+zplug 'wfxr/forgit', defer:1
+zplug "zlsun/solarized-man"
+zplug "pindexis/marker", from:github, as:command, rename-to:marker, hook-build:"./install.py"
+
+# Themes and dircolors {{{
+#zplug "joel-porquet/zsh-dircolors-solarized"
+#zplug "halfo/lambda-mod-zsh-theme", as:theme
+#zplug "agkozak/agkozak-zsh-theme"
+#zplug "zakaziko99/agnosterzak-ohmyzsh-theme", as:theme
+#zplug "eendroroy/alien-minimal"
+#zplug "mafredri/zsh-async", from:github
+#zplug "sindresorhus/pure", use:pure.zsh, from:github, as:theme
+#zplug "bhilburn/powerlevel9k", use:powerlevel9k.zsh-theme
+#zplug "denysdovhan/spaceship-prompt", use:spaceship.zsh, from:github, as:theme
+#zplug "el1t/statusline"
+#zplug 'simnalamburt/shellder', as:theme
+zplug "caiogondim/bullet-train.zsh", use:bullet-train.zsh-theme, defer:3 # defer until other plugins like oh-my-zsh is loaded
+#}}}
+
+# Install plugins if there are plugins that have not been installed
+if ! zplug check --verbose; then
+	printf "Install missing plugins? [y/N]: "
+	if read; then
+		echo; zplug install
+	fi
+fi
+
+zplug load
+
+export MARKER_HOME="$ZPLUG_HOME/repos/pindexis/marker"
+export MARKER_DATA_HOME="$MARKER_HOME/.data"
+source ${MARKER_HOME}/bin/marker.sh
+
+[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
+
+# Setting fd as the default source for fzf
+export FZF_DEFAULT_COMMAND='fd --type f'
+# To apply the command to CTRL-T as well
+export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
+#
+export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --inline-info'
+
+# Use fd (https://github.com/sharkdp/fd) instead of the default find
+# command for listing path candidates.
+# - The first argument to the function ($1) is the base path to start traversal
+# - See the source code (completion.{bash,zsh}) for the details.
+_fzf_compgen_path() {
+  fd --hidden --follow --exclude ".git" . "$1"
+}
+
+# Use fd to generate the list for directory completion
+_fzf_compgen_dir() {
+  fd --type d --hidden --follow --exclude ".git" . "$1"
+}
+
+# fkill - kill process
+fkill() {
+  local pid
+  pid=$(ps -ef | sed 1d | fzf -m | awk '{print $2}')
+
+  if [ "x$pid" != "x" ]
+  then
+    echo $pid | xargs kill -${1:-9}
+  fi
+}
+# fco_preview - checkout git branch/tag, with a preview showing the commits between the tag/branch and HEAD
+fco_preview() {
+  local tags branches target
+  tags=$(
+git tag | awk '{print "\x1b[31;1mtag\x1b[m\t" $1}') || return
+  branches=$(
+git branch --all | grep -v HEAD |
+sed "s/.* //" | sed "s#remotes/[^/]*/##" |
+sort -u | awk '{print "\x1b[34;1mbranch\x1b[m\t" $1}') || return
+  target=$(
+(echo "$tags"; echo "$branches") |
+    fzf --no-hscroll --no-multi --delimiter="\t" -n 2 \
+        --ansi --preview="git log -200 --pretty=format:%s $(echo {+2..} |  sed 's/$/../' )" ) || return
+  git checkout $(echo "$target" | awk '{print $2}')
+}
+# change to the directory of the file
+cdf() {
+   local file
+   local dir
+   file=$(fzf +m -q "$1") && dir=$(dirname "$file") && cd "$dir"
+}
+
 
 # User configuration
 
@@ -96,16 +206,17 @@ source "$ZSH/oh-my-zsh.sh"
 # ssh
 # export SSH_KEY_PATH="~/.ssh/rsa_id"
 
-source "$dotfiles/shell/general/bootstrap.sh"
+source "$dotfiles/shell/common/bootstrap.sh"
 
-if [ -f /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]; then
-	source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
-else
-	echo "zsh syntax-highlighting is missing: apt install zsh-syntax-highlighting"
-fi
 
-# If fzf is installed, use it.
-[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
+# NVM is too slow
+# https://github.com/creationix/nvm/issues/539#issuecomment-245791291
+function enable_nvm {
+	export NVM_DIR="$HOME/.nvm"
+	[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" --no-use # This loads nvm
+	alias node='unalias node ; unalias npm ; nvm use default ; node $@'
+	alias npm='unalias node ; unalias npm ; nvm use default ; npm $@'
+}
 
 # See:
 # https://github.com/tonylambiris/dotfiles/blob/master/dot.zshrc
